use_frameworks!

platform :ios, '12.0'

target 'rapidsnark_Example' do
  pod 'rapidsnark', :path => '../'
  pod 'CircomWitnesscalc', '0.0.1-alpha.2'

  target 'rapidsnark_Tests' do
    inherit! :search_paths


  end
end
